//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Chapter_prefab
    {
        public const string BundleName = "chapter_prefab";
        public const string CHAPTER = "Chapter";
    }
    public class Intro_webm
    {
        public const string BundleName = "intro_webm";
        public const string INTRO = "Intro";
    }
    public class Mainmenu_unity
    {
        public const string BundleName = "mainmenu_unity";
        public const string MAINMENU = "MainMenu";
    }
    public class Mainmenupanel_prefab
    {
        public const string BundleName = "mainmenupanel_prefab";
        public const string MAINMENUPANEL = "MainMenuPanel";
    }
    public class Opening_unity
    {
        public const string BundleName = "opening_unity";
        public const string OPENING = "Opening";
    }
    public class Optionmenupanel_prefab
    {
        public const string BundleName = "optionmenupanel_prefab";
        public const string OPTIONMENUPANEL = "OptionMenuPanel";
    }
    public class Pausepanel_prefab
    {
        public const string BundleName = "pausepanel_prefab";
        public const string PAUSEPANEL = "PausePanel";
    }
    public class Prologue_webm
    {
        public const string BundleName = "prologue_webm";
        public const string PROLOGUE = "Prologue";
    }
    public class Samplescene_unity
    {
        public const string BundleName = "samplescene_unity";
        public const string SAMPLESCENE = "SampleScene";
    }
    public class Volumemenupanel_prefab
    {
        public const string BundleName = "volumemenupanel_prefab";
        public const string VOLUMEMENUPANEL = "VolumeMenuPanel";
    }
}
